# Generated by Django 5.1.13 on 2026-02-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0002_aisttestmeta'),
        ('aist', '0007_remove_aistlaunchconfigaction_unique_constraint'),
    ]

    operations = [
    ]
