# Generated by Django 5.1.13 on 2026-02-16

import re
from urllib.parse import urlsplit, urlunsplit

import django.db.models.deletion
from django.db import migrations, models

GIT_BRANCH = "GIT_BRANCH"
GIT_HASH = "GIT_HASH"
SOURCEFILE_LINK = "sourcefile_link"
PROJECT_VERSION_BLOB_RE = re.compile(
    r"^(?P<prefix>.*?/projects_version/)(?P<id>\d+)(?P<suffix>/files/blob/(?P<subpath>.+))$",
)


def _bulk_attach_findings(project_version_finding, *, version_id: int, finding_ids: list[int]) -> None:
    if not finding_ids:
        return
    rows = [
        project_version_finding(aistprojectversion_id=version_id, finding_id=finding_id)
        for finding_id in set(finding_ids)
    ]
    project_version_finding.objects.bulk_create(rows, ignore_conflicts=True)


def _replace_project_version_id(url: str, new_id: int) -> str | None:
    if not url:
        return None
    parts = urlsplit(url)
    m = PROJECT_VERSION_BLOB_RE.match(parts.path or "")
    if not m:
        return None
    new_path = f"{m.group('prefix')}{new_id}{m.group('suffix')}"
    return urlunsplit((parts.scheme, parts.netloc, new_path, parts.query, parts.fragment))


def _forward_split_versions(apps, schema_editor):
    AISTProjectVersion = apps.get_model("aist", "AISTProjectVersion")
    AISTPipeline = apps.get_model("aist", "AISTPipeline")
    Finding = apps.get_model("dojo", "Finding")
    DojoMeta = apps.get_model("dojo", "DojoMeta")
    ProjectVersionFinding = AISTProjectVersion.findings.through

    # Historical behavior used GIT_HASH for branch refs; move all of them to GIT_BRANCH first.
    AISTProjectVersion.objects.filter(version_type=GIT_HASH).update(version_type=GIT_BRANCH)

    pipelines = (
        AISTPipeline.objects
        .exclude(project_version_id__isnull=True)
        .order_by("created", "id")
    )

    for pipeline in pipelines.iterator():
        pipeline_version = AISTProjectVersion.objects.filter(id=pipeline.project_version_id).first()
        if not pipeline_version:
            continue

        effective_version = pipeline_version

        if pipeline_version.version_type == GIT_BRANCH:
            resolved_commit = (pipeline.resolved_commit or "").strip()
            if not resolved_commit:
                launch_data = pipeline.launch_data or {}
                if isinstance(launch_data, dict):
                    git_data = launch_data.get("git") or {}
                    if isinstance(git_data, dict):
                        resolved_commit = (git_data.get("resolved_commit") or "").strip()

            if resolved_commit:
                hash_version, _ = AISTProjectVersion.objects.get_or_create(
                    project_id=pipeline.project_id,
                    version=resolved_commit,
                    version_type=GIT_HASH,
                    defaults={"resolved_from_branch_id": pipeline_version.id},
                )
                if not hash_version.resolved_from_branch_id:
                    hash_version.resolved_from_branch_id = pipeline_version.id
                    hash_version.save(update_fields=["resolved_from_branch"])

                branch_changed = False
                if (pipeline_version.last_resolved_commit or "") != resolved_commit:
                    pipeline_version.last_resolved_commit = resolved_commit
                    branch_changed = True

                candidate_time = pipeline.updated or pipeline.created
                if candidate_time and (
                    pipeline_version.last_resolved_at is None or candidate_time > pipeline_version.last_resolved_at
                ):
                    pipeline_version.last_resolved_at = candidate_time
                    branch_changed = True

                if branch_changed:
                    pipeline_version.save(update_fields=["last_resolved_commit", "last_resolved_at"])

                if pipeline.project_version_id != hash_version.id:
                    pipeline.project_version_id = hash_version.id
                    pipeline.save(update_fields=["project_version"])

                effective_version = hash_version

        test_ids = list(pipeline.tests.values_list("id", flat=True))
        if not test_ids:
            continue

        finding_ids = list(Finding.objects.filter(test_id__in=test_ids).values_list("id", flat=True))
        if not finding_ids:
            continue

        _bulk_attach_findings(
            ProjectVersionFinding,
            version_id=effective_version.id,
            finding_ids=finding_ids,
        )

        if effective_version.version_type == GIT_HASH and effective_version.resolved_from_branch_id:
            _bulk_attach_findings(
                ProjectVersionFinding,
                version_id=effective_version.resolved_from_branch_id,
                finding_ids=finding_ids,
            )

    # Rewrite old sourcefile_link to point to GIT_HASH version when available for this finding.
    hash_ids_by_finding: dict[int, int] = {}
    fallback_ids_by_finding: dict[int, int] = {}
    for rel in (
        ProjectVersionFinding.objects
        .select_related("aistprojectversion")
        .order_by("finding_id", "aistprojectversion_id")
        .iterator()
    ):
        finding_id = rel.finding_id
        pv = rel.aistprojectversion
        if not pv:
            continue
        if finding_id not in fallback_ids_by_finding:
            fallback_ids_by_finding[finding_id] = pv.id
        if pv.version_type == GIT_HASH:
            hash_ids_by_finding[finding_id] = pv.id

    metas_to_update = []
    for meta in DojoMeta.objects.filter(name=SOURCEFILE_LINK).iterator():
        preferred_pv_id = hash_ids_by_finding.get(meta.finding_id) or fallback_ids_by_finding.get(meta.finding_id)
        if not preferred_pv_id:
            continue
        new_value = _replace_project_version_id(meta.value or "", preferred_pv_id)
        if new_value and new_value != meta.value:
            meta.value = new_value
            metas_to_update.append(meta)

    if metas_to_update:
        DojoMeta.objects.bulk_update(metas_to_update, fields=["value"], batch_size=500)


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("aist", "0011_rename_aisttestmeta_dedup_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="aistprojectversion",
            name="findings",
            field=models.ManyToManyField(blank=True, related_name="aist_project_versions", to="dojo.finding"),
        ),
        migrations.AddField(
            model_name="aistprojectversion",
            name="resolved_from_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_hash_versions",
                to="aist.aistprojectversion",
            ),
        ),
        migrations.AlterField(
            model_name="aistprojectversion",
            name="version_type",
            field=models.CharField(
                choices=[
                    ("GIT_BRANCH", "Git branch"),
                    ("GIT_HASH", "Git commit/hash"),
                    ("FILE_HASH", "File hash (uploaded archive)"),
                ],
                db_index=True,
                default="GIT_BRANCH",
                max_length=16,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="aistprojectversion",
            name="uniq_project_version_per_project",
        ),
        migrations.AddConstraint(
            model_name="aistprojectversion",
            constraint=models.UniqueConstraint(
                fields=("project", "version", "version_type"),
                name="uniq_project_version_type_per_project",
            ),
        ),
        migrations.RunPython(_forward_split_versions, _noop_reverse),
        migrations.RemoveField(
            model_name="aistpipeline",
            name="resolved_commit",
        ),
    ]
