# Generated by Django 5.1.13 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


def _extract_entry_finding_id(entry: dict) -> int | None:
    if not isinstance(entry, dict):
        return None
    original = entry.get("originalFinding")
    if not isinstance(original, dict):
        return None
    raw_id = original.get("id")
    try:
        value = int(raw_id)
    except (TypeError, ValueError):
        return None
    return value if value > 0 else None


def _iter_payload_entries(payload: dict) -> list[tuple[str, dict]]:
    results = payload.get("results")
    if not isinstance(results, dict):
        return []

    mapping: dict[str, tuple[str, ...]] = {
        "true_positive": ("true_positives",),
        "false_positive": ("false_positives",),
        "uncertain": ("uncertainly", "uncertain"),
    }
    entries: list[tuple[str, dict]] = []
    for verdict, keys in mapping.items():
        for key in keys:
            items = results.get(key)
            if not isinstance(items, list):
                continue
            for item in items:
                if isinstance(item, dict):
                    entries.append((verdict, item))
    return entries


def _forward_fill_ai_finding_responses(apps, schema_editor):
    AISTAIResponse = apps.get_model("aist", "AISTAIResponse")
    AISTAIFindingResponse = apps.get_model("aist", "AISTAIFindingResponse")
    Finding = apps.get_model("dojo", "Finding")

    for ai_response in AISTAIResponse.objects.select_related("pipeline__project").iterator():
        payload = ai_response.payload or {}
        entries = _iter_payload_entries(payload)
        if not entries:
            continue

        candidate_ids: set[int] = set()
        for _, entry in entries:
            finding_id = _extract_entry_finding_id(entry)
            if finding_id:
                candidate_ids.add(finding_id)
        if not candidate_ids:
            continue

        valid_ids = set(
            Finding.objects.filter(
                id__in=candidate_ids,
                test__engagement__product_id=ai_response.pipeline.project.product_id,
            ).values_list("id", flat=True),
        )
        if not valid_ids:
            continue

        seen: set[int] = set()
        for verdict, entry in entries:
            finding_id = _extract_entry_finding_id(entry)
            if not finding_id or finding_id not in valid_ids:
                continue
            if finding_id in seen:
                continue
            seen.add(finding_id)
            AISTAIFindingResponse.objects.update_or_create(
                pipeline_id=ai_response.pipeline_id,
                finding_id=finding_id,
                defaults={
                    "source_response_id": ai_response.id,
                    "verdict": verdict,
                    "title": (entry.get("title") or "")[:512],
                    "summary": entry.get("reasoning") or "",
                    "references": entry.get("references") if isinstance(entry.get("references"), list) else [],
                    "epss_score": entry.get("epssScore"),
                    "impact_score": entry.get("impactScore"),
                    "exploitability_score": entry.get("exploitabilityScore"),
                    "uncertainty_level": entry.get("uncertaintyLevel"),
                    "uncertainty_spread": entry.get("uncertaintySpread"),
                    "exploit_code_maturity": (entry.get("exploitCodeMaturity") or "")[:64],
                },
            )


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("aist", "0012_project_version_branch_hash_split"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISTAIFindingResponse",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verdict", models.CharField(choices=[("true_positive", "True Positive"), ("false_positive", "False Positive"), ("uncertain", "Uncertain")], db_index=True, max_length=32)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("summary", models.TextField(blank=True, default="")),
                ("references", models.JSONField(blank=True, default=list)),
                ("epss_score", models.FloatField(blank=True, null=True)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("exploitability_score", models.FloatField(blank=True, null=True)),
                ("uncertainty_level", models.FloatField(blank=True, null=True)),
                ("uncertainty_spread", models.FloatField(blank=True, null=True)),
                ("exploit_code_maturity", models.CharField(blank=True, default="", max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aist_ai_responses",
                        to="dojo.finding",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_finding_responses",
                        to="aist.aistpipeline",
                    ),
                ),
                (
                    "source_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finding_responses",
                        to="aist.aistairesponse",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated"],
                "indexes": [models.Index(fields=["pipeline", "verdict"], name="aist_aistai_pipelin_3868d4_idx"), models.Index(fields=["pipeline", "finding"], name="aist_aistai_pipelin_6a546f_idx")],
                "constraints": [models.UniqueConstraint(fields=("pipeline", "finding"), name="uniq_aist_ai_finding_per_pipeline")],
            },
        ),
        migrations.RunPython(_forward_fill_ai_finding_responses, _noop_reverse),
    ]
