# Generated by Django 4.2 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aist", "0013_aistaifindingresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aistlaunchconfigaction",
            name="trigger_status",
            field=models.CharField(
                choices=[
                    ("SAST_LAUNCHED", "Launched"),
                    ("UPLOADING_RESULTS", "Uploading Results"),
                    ("FINDING_POSTPROCESSING", "Finding post-processing"),
                    ("WAITING_DEDUPLICATION_TO_FINISH", "Waiting Deduplication To Finish"),
                    ("WAITING_CONFIRMATION_TO_PUSH_TO_AI", "Waiting Confirmation To Push to AI"),
                    ("PUSH_TO_AI", "Push to AI"),
                    ("WAITING_RESULT_FROM_AI", "Waiting Result From AI"),
                    ("FINISHED", "Finished"),
                    ("FINISHED_WITH_WARNINGS", "Finished With Warnings"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="aistpipeline",
            name="status",
            field=models.CharField(
                choices=[
                    ("SAST_LAUNCHED", "Launched"),
                    ("UPLOADING_RESULTS", "Uploading Results"),
                    ("FINDING_POSTPROCESSING", "Finding post-processing"),
                    ("WAITING_DEDUPLICATION_TO_FINISH", "Waiting Deduplication To Finish"),
                    ("WAITING_CONFIRMATION_TO_PUSH_TO_AI", "Waiting Confirmation To Push to AI"),
                    ("PUSH_TO_AI", "Push to AI"),
                    ("WAITING_RESULT_FROM_AI", "Waiting Result From AI"),
                    ("FINISHED", "Finished"),
                    ("FINISHED_WITH_WARNINGS", "Finished With Warnings"),
                ],
                default="FINISHED",
                max_length=64,
            ),
        ),
    ]
