# Generated by Django 5.1.13 on 2026-02-20

import django.db.models.deletion
from django.db import migrations, models


def forwards_link_organizations_to_product_types(apps, schema_editor):
    Organization = apps.get_model("aist", "Organization")
    AISTProject = apps.get_model("aist", "AISTProject")
    Product = apps.get_model("dojo", "Product")
    ProductType = apps.get_model("dojo", "Product_Type")

    for organization in Organization.objects.all().iterator():
        if organization.product_type_id:
            product_type = ProductType.objects.get(id=organization.product_type_id)
        else:
            product_type, _ = ProductType.objects.get_or_create(name=organization.name)
            organization.product_type_id = product_type.id
            organization.save(update_fields=["product_type"])

        product_ids = list(
            AISTProject.objects.filter(organization_id=organization.id)
            .values_list("product_id", flat=True)
            .distinct(),
        )
        if product_ids:
            Product.objects.filter(id__in=product_ids).exclude(prod_type_id=product_type.id).update(
                prod_type_id=product_type.id,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0259_locations"),
        ("aist", "0014_add_finished_with_warnings_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="organization",
            name="product_type",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aist_organization",
                to="dojo.product_type",
            ),
        ),
        migrations.RunPython(forwards_link_organizations_to_product_types, migrations.RunPython.noop),
    ]
