# Generated by Django 5.2.11 on 2026-03-18 18:17

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aist", "0023_remove_legacy_credential_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgintegration",
            name="secret",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="workitemprovider",
            name="api_token",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=""),
        ),
    ]
