# Generated by Django 5.2.11 on 2026-04-02 12:17

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0026_version_script_and_remove_project_active_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemprovider',
            name='vpn_integration',
            field=models.ForeignKey(blank=True, help_text='VPN integration to use when connecting to this provider. Must belong to the same organization.', limit_choices_to={'integration_type': 'VPN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_work_item_providers', to='aist.orgintegration'),
        ),
        migrations.AlterField(
            model_name='orgintegration',
            name='integration_type',
            field=models.CharField(choices=[('GITLAB', 'GitLab'), ('GITHUB', 'GitHub'), ('SLACK', 'Slack'), ('EMAIL', 'Email'), ('VPN', 'VPN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='projectintegrationoverride',
            name='integration_type',
            field=models.CharField(choices=[('GITLAB', 'GitLab'), ('GITHUB', 'GitHub'), ('SLACK', 'Slack'), ('EMAIL', 'Email'), ('VPN', 'VPN')], max_length=32),
        ),
        migrations.CreateModel(
            name='OrgIntegrationVPNSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovpn_content', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('ca_cert', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('client_cert', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('client_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('tls_auth_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('vpn_username', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('vpn_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_secret', to='aist.orgintegration')),
            ],
        ),
    ]
