# Generated by Django 5.2.11 on 2026-04-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0027_vpn_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgintegrationvpnsecret',
            name='tls_key_type',
            field=models.CharField(blank=True, default='tls-auth', max_length=16),
        ),
    ]
