# Generated by Django 5.2.11 on 2026-07-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aist", "0035_aistapitoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgMembershipHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("invited", "Invited"), ("role_changed", "Role changed"), ("removed", "Removed")], max_length=32)),
                ("previous_role", models.IntegerField(blank=True, null=True)),
                ("new_role", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="org_membership_actions_performed", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="membership_history", to="aist.organization")),
                ("target_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="org_membership_history_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Org membership history",
                "verbose_name_plural": "Org membership history",
                "ordering": ["-created"],
                "indexes": [models.Index(fields=["organization", "-created"], name="org_membership_hist_org_idx"), models.Index(fields=["target_user", "-created"], name="org_membership_hist_user_idx")],
            },
        ),
    ]
