# Generated by Django 5.2.11 on 2026-08-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aist", "0046_dast_target_project_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="DastRunMetadata",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(max_length=255)),
                ("target_id", models.CharField(max_length=255)),
                ("stand_id", models.CharField(max_length=255)),
                ("product_family", models.CharField(blank=True, max_length=64, null=True)),
                ("tier", models.CharField(blank=True, max_length=64, null=True)),
                ("run_type", models.CharField(blank=True, max_length=64, null=True)),
                ("target_host", models.CharField(blank=True, max_length=255, null=True)),
                ("scan_started", models.DateTimeField(blank=True, null=True)),
                ("scan_finished", models.DateTimeField(blank=True, null=True)),
                ("coverage_unit", models.CharField(blank=True, max_length=64, null=True)),
                ("discovered", models.PositiveIntegerField(blank=True, null=True)),
                ("reachable", models.PositiveIntegerField(blank=True, null=True)),
                ("analysed", models.PositiveIntegerField(blank=True, null=True)),
                ("planned", models.PositiveIntegerField(blank=True, null=True)),
                ("analysed_names", models.JSONField(blank=True, default=None, null=True)),
                ("beyond_plan_names", models.JSONField(blank=True, default=None, null=True)),
                ("input_tokens", models.BigIntegerField(blank=True, null=True)),
                ("output_tokens", models.BigIntegerField(blank=True, null=True)),
                ("thinking_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cache_creation_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cache_read_tokens", models.BigIntegerField(blank=True, null=True)),
                ("model_calls", models.PositiveIntegerField(blank=True, null=True)),
                ("token_by_phase", models.JSONField(blank=True, default=None, null=True)),
                ("token_by_agent_type", models.JSONField(blank=True, default=None, null=True)),
                ("token_accounting_consistent", models.BooleanField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("pipeline", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dast_run_metadata", to="aist.aistpipeline")),
            ],
        ),
    ]
