# Generated by Django 5.1.13 on 2026-01-21 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aist", "0004_organization_aistproject_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="aistpipeline",
            name="resolved_commit",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="aistproject",
            name="ai_default_filter",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="aistprojectversion",
            name="last_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aistprojectversion",
            name="last_resolved_commit",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_default_filter",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="AISTProjectLaunchConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("params", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="launch_configs", to="aist.aistproject")),
            ],
        ),
        migrations.CreateModel(
            name="LaunchSchedule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cron_expression", models.CharField(help_text="Cron expression in standard 5-field format (e.g. '0 15 * * 1' for Mondays at 15:00).", max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("max_concurrent_per_worker", models.PositiveIntegerField(default=1, help_text="Maximum number of concurrent pipeline runs per worker for this schedule.")),
                ("last_run_at", models.DateTimeField(blank=True, help_text="Timestamp of the last time this schedule launched pipelines.", null=True)),
                ("launch_config", models.OneToOneField(help_text="Anchor launch config. Project is derived from launch_config.project.", on_delete=django.db.models.deletion.PROTECT, related_name="launch_schedule", to="aist.aistprojectlaunchconfig")),
            ],
            options={
                "verbose_name": "Launch Schedule",
                "verbose_name_plural": "Launch Schedules",
            },
        ),
        migrations.CreateModel(
            name="PipelineLaunchQueue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("dispatched", models.BooleanField(db_index=True, default=False)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("launch_config", models.ForeignKey(blank=True, help_text="Launch config used to build pipeline_args snapshot.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="launch_queue_items", to="aist.aistprojectlaunchconfig")),
                ("pipeline", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="launch_queue_item", to="aist.aistpipeline")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aist.aistproject")),
                ("schedule", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="aist.launchschedule")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddConstraint(
            model_name="aistprojectlaunchconfig",
            constraint=models.UniqueConstraint(fields=("project", "name"), name="uniq_aist_launch_cfg_name_per_project"),
        ),
    ]
