# Generated by Django 5.1.11 on 2025-10-22 15:13

import dojo.aist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0011_repositoryinfo_scmgithubbinding_scmgitlabbinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistprojectversion',
            name='source_archive',
            field=models.FileField(blank=True, null=True, upload_to=dojo.aist.models.AISTProjectVersion._upload_to),
        ),
        migrations.AddField(
            model_name='aistprojectversion',
            name='source_archive_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aistprojectversion',
            name='version_type',
            field=models.CharField(choices=[('GIT_HASH', 'Git commit/hash'), ('FILE_HASH', 'File hash (uploaded archive)')], db_index=True, default='GIT_HASH', max_length=16),
        ),
    ]
