# Generated by Django 5.1.11 on 2025-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0012_aistprojectversion_source_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aistprojectversion',
            name='source_archive_sha256',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
