---
services:
  nginx:
    environment:
      USE_TLS: 'true'
      GENERATE_TLS_CERTIFICATE: 'true'
  uwsgi:
    environment:
      DD_SESSION_COOKIE_SECURE: 'True'
      DD_CSRF_COOKIE_SECURE: 'True'
