# Generated by Django 5.1.13 on 2026-01-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0247_merge_20251105_0928'),
        ('dojo', '0255_remove_system_settings_product_grade'),
    ]

    operations = [
    ]
