# Generated by Django 5.1.11 on 2025-09-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0999_test_deduplication_complete_processedfinding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdeduplicationprogress',
            name='test',
        ),
        migrations.DeleteModel(
            name='ProcessedFinding',
        ),
        migrations.DeleteModel(
            name='TestDeduplicationProgress',
        ),
    ]
