from django.urls import path

from aist.api import (
    AISTAuthLoginAPI,
    AISTAuthLogoutAllAPI,
    AISTAuthLogoutAPI,
    AISTCalendarEventDetailAPI,
    AISTCalendarEventsAPI,
    AISTCweDetailAPI,
    AISTFindingBulkStatusAPI,
    AISTFindingExportAPI,
    AISTFindingListAPI,
    AISTFindingMarkDuplicateAPI,
    AISTFindingNotesAPI,
    AISTFindingRiskApprovalAPI,
    AISTFindingTimelineAPI,
    AISTMeAPI,
    AISTMeChangePasswordAPI,
    AISTProjectDetailAPI,
    AISTProjectListAPI,
    AISTProjectRegenerateAnalysisAPI,
    FindingWorkItemDetailAPI,
    FindingWorkItemListCreateAPI,
    GithubConnectCallbackAPI,
    GithubImportConnectStartAPI,
    GithubImportExecuteAPI,
    GithubImportOptionsAPI,
    GithubImportRepositoriesAPI,
    GithubProjectConnectStartAPI,
    GithubProjectLinkRepositoryAPI,
    GithubProjectRepositoriesAPI,
    GithubProjectStatusAPI,
    LaunchConfigDashboardListAPI,
    LaunchScheduleBulkDisableAPI,
    LaunchScheduleDetailAPI,
    LaunchScheduleListAPI,
    LaunchSchedulePreviewAPI,
    LaunchScheduleRunOnceAPI,
    OrganizationCreateAPI,
    OrgIntegrationDetailAPI,
    OrgIntegrationListCreateAPI,
    OrgIntegrationValidateAPI,
    OrgIntegrationValidateStatusAPI,
    PipelineAPI,
    PipelineLaunchQueueClearDispatchedAPI,
    PipelineLaunchQueueDetailAPI,
    PipelineLaunchQueueListAPI,
    PipelineListAPI,
    PipelineStartAPI,
    ProjectIntegrationOverrideAPI,
    ProjectIntegrationOverrideDetailAPI,
    ProjectLaunchConfigActionDetailAPI,
    ProjectLaunchConfigActionListCreateAPI,
    ProjectLaunchConfigDetailAPI,
    ProjectLaunchConfigListCreateAPI,
    ProjectLaunchConfigStartAPI,
    ProjectLaunchScheduleUpsertAPI,
    ProjectVersionCreateAPI,
    ProjectVersionFileBlobAPI,
    ProjectVersionScriptUpdateAPI,
    WorkItemProviderDetailAPI,
    WorkItemProviderListCreateAPI,
    WorkItemProviderSyncAPI,
    WorkItemProviderValidateAPI,
    WorkItemProviderValidateStatusAPI,
)
from aist.api.ai import (
    AIDeleteResponseAPI,
    AIFindingResponseListAPI,
    AIPipelineCallbackAPI,
    AISendRequestAPI,
    LocalTriageCompleteAPI,
)
from aist.api.gerrit_integration import ImportProjectFromGerritAPI
from aist.api.gitea_integration import ImportProjectFromGiteaAPI
from aist.api.gitlab_integration import ImportProjectFromGitlabAPI
from aist.api.pipelines import (
    ExportAIResultsAPI,
    PipelineDeduplicationProgressAPI,
    PipelineEnrichProgressAPI,
    PipelineLogsDownloadAPI,
    PipelineLogsFullAPI,
    PipelineLogsProgressiveAPI,
    PipelineLogsStreamAPI,
    PipelineLogsStreamRedisAPI,
    PipelineSourceInfoAPI,
    PipelineStatusStreamAPI,
    PipelineStopAPI,
)
from aist.api.projects import (
    AISTDefaultAnalyzersAPI,
    AISTProjectActiveScriptAPI,
    AISTProjectMetaAPI,
    AISTProjectScriptDetailAPI,
    AISTProjectScriptListCreateAPI,
)
from aist.api.tags import AvailableFindingTagsAPI

app_name = "aist_api"
urlpatterns = [
    path("auth/login/", AISTAuthLoginAPI.as_view(), name="auth_login"),
    path("me/", AISTMeAPI.as_view(), name="me"),
    path("me/change-password/", AISTMeChangePasswordAPI.as_view(), name="me_change_password"),
    path("auth/logout/", AISTAuthLogoutAPI.as_view(), name="auth_logout"),
    path("auth/logout-all/", AISTAuthLogoutAllAPI.as_view(), name="auth_logout_all"),
    path("calendar/events/", AISTCalendarEventsAPI.as_view(), name="calendar_events"),
    path("calendar/events/<path:event_id>/", AISTCalendarEventDetailAPI.as_view(), name="calendar_event_detail"),
    path("projects/", AISTProjectListAPI.as_view(), name="project_list"),
    path("projects/<int:project_id>/", AISTProjectDetailAPI.as_view(), name="project_detail"),
    path("projects/<int:project_id>/meta/", AISTProjectMetaAPI.as_view(), name="project_meta"),
    path(
        "projects/<int:project_id>/regenerate-analysis/",
        AISTProjectRegenerateAnalysisAPI.as_view(),
        name="project_regenerate_analysis",
    ),
    path(
        "projects/<int:project_id>/scripts/",
        AISTProjectScriptListCreateAPI.as_view(),
        name="project_script_list_create",
    ),
    path(
        "projects/<int:project_id>/scripts/<int:script_id>/",
        AISTProjectScriptDetailAPI.as_view(),
        name="project_script_detail",
    ),
    path(
        "projects/<int:project_id>/active-script/",
        AISTProjectActiveScriptAPI.as_view(),
        name="project_active_script",
    ),
    path("projects/default-analyzers/", AISTDefaultAnalyzersAPI.as_view(), name="default_analyzers"),
    path("pipelines/start/", PipelineStartAPI.as_view(), name="pipeline_start"),
    path("pipelines/<str:pipeline_id>", PipelineAPI.as_view(), name="pipeline_status"),
    path("pipelines/<str:pipeline_id>/stop/", PipelineStopAPI.as_view(), name="pipeline_stop"),
    path("pipelines/<str:pipeline_id>/source-info/", PipelineSourceInfoAPI.as_view(), name="pipeline_source_info"),
    path("pipelines/<str:pipeline_id>/send-request-to-ai/", AISendRequestAPI.as_view(), name="pipeline_send_request"),
    path("pipelines/<str:pipeline_id>/callback/", AIPipelineCallbackAPI.as_view(), name="pipeline_callback"),
    path("pipelines/<str:pipeline_id>/local-triage-complete/", LocalTriageCompleteAPI.as_view(), name="pipeline_local_triage_complete"),
    path("ai-finding-responses/", AIFindingResponseListAPI.as_view(), name="ai_finding_responses"),
    path(
        "pipelines/<str:pipeline_id>/ai-response/<int:response_id>/",
        AIDeleteResponseAPI.as_view(),
        name="pipeline_ai_response_delete",
    ),
    path(
        "pipelines/<str:pipeline_id>/export-ai-results/",
        ExportAIResultsAPI.as_view(),
        name="pipeline_export_ai_results",
    ),
    path("pipelines/", PipelineListAPI.as_view(), name="pipelines"),
    path(
        "pipelines/<str:pipeline_id>/logs/progressive/",
        PipelineLogsProgressiveAPI.as_view(),
        name="pipeline_logs_progressive",
    ),
    path(
        "pipelines/<str:pipeline_id>/logs/",
        PipelineLogsFullAPI.as_view(),
        name="pipeline_logs_full",
    ),
    path(
        "pipelines/<str:pipeline_id>/logs/download/",
        PipelineLogsDownloadAPI.as_view(),
        name="pipeline_logs_download",
    ),
    path(
        "pipelines/<str:pipeline_id>/logs/stream/",
        PipelineLogsStreamAPI.as_view(),
        name="pipeline_logs_stream",
    ),
    path(
        "pipelines/<str:pipeline_id>/logs/stream-redis/",
        PipelineLogsStreamRedisAPI.as_view(),
        name="pipeline_logs_stream_redis",
    ),
    path(
        "pipelines/<str:pipeline_id>/progress/status/",
        PipelineStatusStreamAPI.as_view(),
        name="pipeline_status_stream",
    ),
    path(
        "pipelines/<str:pipeline_id>/progress/deduplication/",
        PipelineDeduplicationProgressAPI.as_view(),
        name="pipeline_deduplication_progress",
    ),
    path(
        "pipelines/<str:pipeline_id>/progress/enrichment/",
        PipelineEnrichProgressAPI.as_view(),
        name="pipeline_enrich_progress",
    ),
    path(
        "organizations/",
        OrganizationCreateAPI.as_view(),
        name="organization_create",
    ),
    path("findings/", AISTFindingListAPI.as_view(), name="finding_list"),
    path("findings/timeline/", AISTFindingTimelineAPI.as_view(), name="finding_timeline"),
    path("findings/bulk-status/", AISTFindingBulkStatusAPI.as_view(), name="finding_bulk_status"),
    path("findings/<int:finding_id>/notes/", AISTFindingNotesAPI.as_view(), name="finding_notes"),
    path("findings/<int:finding_id>/risk-approval/", AISTFindingRiskApprovalAPI.as_view(), name="finding_risk_approval"),
    path("findings/<int:finding_id>/export/", AISTFindingExportAPI.as_view(), name="finding_export"),
    path("findings/<int:finding_id>/mark-duplicate/", AISTFindingMarkDuplicateAPI.as_view(), name="finding_mark_duplicate"),
    path(
        "projects_version/<int:project_version_id>/files/blob/<path:subpath>",
        ProjectVersionFileBlobAPI.as_view(),
        name="project_version_file_blob",
    ),
    path(
        "projects/<int:project_id>/versions",
        ProjectVersionCreateAPI.as_view(),
        name="project_version_create",
    ),
    path(
        "projects/<int:project_id>/versions/<int:version_id>/script",
        ProjectVersionScriptUpdateAPI.as_view(),
        name="project_version_script_update",
    ),
    path("import_project_from_gitlab/", ImportProjectFromGitlabAPI.as_view(), name="import_project_from_gitlab"),
    path("import_project_from_gerrit/", ImportProjectFromGerritAPI.as_view(), name="import_project_from_gerrit"),
    path("import_project_from_gitea/", ImportProjectFromGiteaAPI.as_view(), name="import_project_from_gitea"),
    path("github/import/options/", GithubImportOptionsAPI.as_view(), name="github_import_options"),
    path("github/import/connect/start/", GithubImportConnectStartAPI.as_view(), name="github_import_connect_start"),
    path("github/import/connect/callback/", GithubConnectCallbackAPI.as_view(), name="github_connect_callback"),
    path("github/import/repositories/", GithubImportRepositoriesAPI.as_view(), name="github_import_repositories"),
    path("github/import/execute/", GithubImportExecuteAPI.as_view(), name="github_import_execute"),
    path("projects/<int:project_id>/github/status/", GithubProjectStatusAPI.as_view(), name="project_github_status"),
    path(
        "projects/<int:project_id>/github/connect/start/",
        GithubProjectConnectStartAPI.as_view(),
        name="project_github_connect_start",
    ),
    path(
        "projects/<int:project_id>/github/repositories/",
        GithubProjectRepositoriesAPI.as_view(),
        name="project_github_repositories",
    ),
    path(
        "projects/<int:project_id>/github/link-repository/",
        GithubProjectLinkRepositoryAPI.as_view(),
        name="project_github_link_repository",
    ),
    path("findings/tags/", AvailableFindingTagsAPI.as_view(), name="finding_tags"),
    path(
        "findings/<int:finding_id>/work-items/",
        FindingWorkItemListCreateAPI.as_view(),
        name="finding_work_item_list_create",
    ),
    path(
        "findings/<int:finding_id>/work-items/<int:link_id>/",
        FindingWorkItemDetailAPI.as_view(),
        name="finding_work_item_detail",
    ),
    path(
        "organizations/<int:org_id>/integrations/",
        OrgIntegrationListCreateAPI.as_view(),
        name="org_integration_list_create",
    ),
    path(
        "integrations/<int:integration_id>/",
        OrgIntegrationDetailAPI.as_view(),
        name="org_integration_detail",
    ),
    path(
        "integrations/<int:integration_id>/validate/",
        OrgIntegrationValidateAPI.as_view(),
        name="org_integration_validate",
    ),
    path(
        "integrations/<int:integration_id>/validate/<str:task_id>/",
        OrgIntegrationValidateStatusAPI.as_view(),
        name="org_integration_validate_status",
    ),
    path(
        "projects/<int:project_id>/integration-overrides/",
        ProjectIntegrationOverrideAPI.as_view(),
        name="project_integration_overrides",
    ),
    path(
        "projects/<int:project_id>/integration-overrides/<str:integration_type>/",
        ProjectIntegrationOverrideDetailAPI.as_view(),
        name="project_integration_override_detail",
    ),
    path(
        "organizations/<int:org_id>/work-item-providers/",
        WorkItemProviderListCreateAPI.as_view(),
        name="work_item_provider_list_create",
    ),
    path(
        "work-item-providers/<int:provider_id>/",
        WorkItemProviderDetailAPI.as_view(),
        name="work_item_provider_detail",
    ),
    path(
        "work-item-providers/<int:provider_id>/validate/",
        WorkItemProviderValidateAPI.as_view(),
        name="work_item_provider_validate",
    ),
    path(
        "work-item-providers/<int:provider_id>/validate/<str:task_id>/",
        WorkItemProviderValidateStatusAPI.as_view(),
        name="work_item_provider_validate_status",
    ),
    path(
        "work-item-providers/<int:provider_id>/sync/",
        WorkItemProviderSyncAPI.as_view(),
        name="work_item_provider_sync",
    ),
    path("cwe/<int:cwe_id>/", AISTCweDetailAPI.as_view(), name="cwe_detail"),
    path(
        "projects/<int:project_id>/launch-configs/",
        ProjectLaunchConfigListCreateAPI.as_view(),
        name="project_launch_config_list_create",
    ),
    path(
        "projects/<int:project_id>/launch-configs/<int:config_id>/",
        ProjectLaunchConfigDetailAPI.as_view(),
        name="project_launch_config_detail",
    ),
    path(
        "projects/<int:project_id>/launch-configs/<int:config_id>/actions/",
        ProjectLaunchConfigActionListCreateAPI.as_view(),
        name="project_launch_config_action_list_create",
    ),
    path(
        "projects/<int:project_id>/launch-configs/<int:config_id>/actions/<int:action_id>/",
        ProjectLaunchConfigActionDetailAPI.as_view(),
        name="project_launch_config_action_detail",
    ),
    path(
        "projects/<int:project_id>/launch-configs/<int:config_id>/start/",
        ProjectLaunchConfigStartAPI.as_view(),
        name="project_launch_config_start",
    ),
    path(
        "launch-configs/",
        LaunchConfigDashboardListAPI.as_view(),
        name="launch_config_dashboard_list",
    ),
    path(
        "projects/<int:project_id>/launch-schedule/",
        ProjectLaunchScheduleUpsertAPI.as_view(),
        name="project_launch_schedule_upsert",
    ),
    path(
        "launch-schedules/",
        LaunchScheduleListAPI.as_view(),
        name="launch_schedule_list",
    ),
    path(
        "launch-schedules/<int:launch_schedule_id>/",
        LaunchScheduleDetailAPI.as_view(),
        name="launch_schedule_detail",
    ),
path("launch-schedules/preview/", LaunchSchedulePreviewAPI.as_view(), name="launch_schedule_preview"),
path("launch-schedules/bulk-disable/", LaunchScheduleBulkDisableAPI.as_view(), name="launch_schedule_bulk_disable"),
path("launch-queue/", PipelineLaunchQueueListAPI.as_view(), name="pipeline_launch_queue_list"),
path("launch-queue/clear-dispatched/", PipelineLaunchQueueClearDispatchedAPI.as_view(), name="pipeline_launch_queue_clear_dispatched"),
path("launch-queue/<int:queue_id>/", PipelineLaunchQueueDetailAPI.as_view(), name="pipeline_launch_queue_detail"),
path(
    "launch-schedules/<int:launch_schedule_id>/run-once/",
    LaunchScheduleRunOnceAPI.as_view(),
    name="launch_schedule_run_once",
),
]
