import type { Finding } from "../types";

export const mockFindings: Finding[] = [
  {
    id: 123,
    title: "Cleartext Storage of SSH Private Key (CWE-312)",
    severity: "Critical",
    active: true,
    product: "Core Platform",
    productId: 10,
    filePath: "cloud/ams/deploy/ams_service/crash_receiver_key",
    line: 1,
    tool: "horusec-27108f5d",
    aiVerdict: "true_positive",
    snippetPreview: "-----BEGIN OPENSSH PRIVATE KEY-----",
    riskStates: ["risk_accepted", "under_review"],
    projectVersionId: 44,
  },
  {
    id: 124,
    title: "Public Certificate in Version Control",
    severity: "High",
    active: true,
    product: "Video Stack",
    productId: 11,
    filePath: "open/vms/libs/nx_vms_common/static-resources/trusted_certificates/AmazonRootCA4.pem",
    line: 1,
    tool: "horusec-27108f5d",
    aiVerdict: "false_positive",
    snippetPreview: "-----BEGIN CERTIFICATE-----",
    riskStates: ["mitigated"],
    projectVersionId: 44,
  },
  {
    id: 125,
    title: "Public SSH Key in Repository (CWE-798)",
    severity: "Medium",
    active: false,
    product: "Payments API",
    productId: 12,
    filePath: "cloud/ams/deploy/ams_service_crash_receiver/crash_receiver_key.pub",
    line: 1,
    tool: "horusec-27108f5d",
    aiVerdict: "false_positive",
    snippetPreview: "AAAAB3NzaC1yc2EAAAADAQABAAABg",
    riskStates: ["risk_accepted"],
    projectVersionId: 44,
  },
];
